module.exports = {
   BAD_DATA_VALIDATION: 'BAD_DATA_VALIDATION',
   BAD_USER_INPUT: 'BAD_USER_INPUT',
   INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
   UNAUTHENTICATED: 'UNAUTHENTICATED',
   FORBIDDEN: 'FORBIDDEN',
}
